#!/bin/bash
# Transfer SRA download fix to cluster

echo "Transferring SRA download fix to cluster..."
echo "🔧 SRA DOWNLOAD FIXES:"
echo "1. ✅ Enhanced SRA downloader with multiple fallback methods"
echo "2. ✅ Entrez API integration for SRA data search"
echo "3. ✅ SRA Toolkit installation script"
echo "4. ✅ Alternative download methods (Run Browser, HTTP)"
echo "5. ✅ Proper error handling and logging"
echo "6. ✅ Based on official NCBI documentation"
echo ""

echo "Transferring files..."
scp src/sra_download_fix.py ul_oqn09@uc3.scc.kit.edu:~/als_foundation_model/src/
scp src/parallel_optimized_pipeline.py ul_oqn09@uc3.scc.kit.edu:~/als_foundation_model/src/
scp scripts/install_sra_toolkit.sh ul_oqn09@uc3.scc.kit.edu:~/als_foundation_model/scripts/

echo "Transfer complete!"
echo ""
echo "🚀 READY TO FIX SRA DOWNLOAD ISSUES!"
echo ""
echo "On the cluster, run these commands:"
echo ""
echo "1. Install SRA Toolkit:"
echo "   cd ~/als_foundation_model"
echo "   chmod +x scripts/install_sra_toolkit.sh"
echo "   ./scripts/install_sra_toolkit.sh"
echo ""
echo "2. Test SRA Toolkit:"
echo "   export PATH=\"\$HOME/sra_toolkit/bin:\$PATH\""
echo "   prefetch --version"
echo "   fasterq-dump --version"
echo ""
echo "3. Run the updated pipeline:"
echo "   sbatch scripts/run_parallel_optimized_pipeline.slurm"
echo ""
echo "Expected improvements:"
echo "- ✅ SRA downloads will work (no more 'esearch' errors)"
echo "- ✅ Multiple fallback methods for SRA data"
echo "- ✅ Better error handling and logging"
echo "- ✅ Proper SRA to FASTQ conversion"
echo "- ✅ Entrez API integration for metadata"
echo ""
echo "The pipeline will now:"
echo "1. 🔍 Search for SRA data using Entrez API"
echo "2. 📥 Download SRA files using prefetch"
echo "3. 🔄 Convert SRA to FASTQ using fasterq-dump"
echo "4. 📊 Extract metadata for each run"
echo "5. 🛡️ Handle errors gracefully with fallbacks"
